title: Hi, I'm Yawar Ashraf!
description: I'm a UofT New Grad Exploring Exciting Opportunities Building AI to solve real-world problems. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
logo: assets/img/algonquinYawar.png
