title: Yawar Ashraf
description: I'm a fourth Year student at the Unversity of Toronto studying Engineering Science in the Machine Intelligence option with a Minor in Robotics. I have extensive experience in AI, software and robotics through many projects and internships.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
logo: assets/img/algonquinYawar.png