title: Yawar Ashraf
description: I'm a fourth Year student at the Unversity of Toronto studying Engineering Science in the Machine Intelligence option.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
logo: assets/img/headShot.jpg